image:
  file: .gitpod.dockerfile
tasks:
 - init: . ${GITPOD_REPO_ROOT}/.theia/init_tasks.sh    
vscode:
  extensions:
    - ms-python.python@2019.8.30787
    - formulahendry.auto-close-tag@0.5.9
    - mkaufman.HTMLHint@0.10.0
    - eventyret.bootstrap-4-cdn-snippet@1.9.0
    - esbenp.prettier-vscode@5.7.1
    - kevinglasson.cornflakes-linter@0.5.1

